In [1]:
using Plots

In [13]:
N = 10
D1 = speye(N-1,N) - spdiagm(ones(N-1),1,N-1,N)
D = [ kron(D1, speye(N)); kron(speye(N), D1) ]
i, j = N*1 + 2, N*7+7
b = zeros(N^2); b[i], b[j] = 1, -1
v = (D' * D) \ b
v[i] - v[j]

1.6089912417307297

In [5]:
full(spdiagm(ones(N-1),1,N-1,N))

9×10 Array{Float64,2}:
 0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0

In [8]:
full(D)

180×100 Array{Float64,2}:
 1.0  0.0  0.0  0.0  0.0  0.0  0.0  …   0.0   0.0   0.0   0.0   0.0   0.0
 0.0  1.0  0.0  0.0  0.0  0.0  0.0      0.0   0.0   0.0   0.0   0.0   0.0
 0.0  0.0  1.0  0.0  0.0  0.0  0.0      0.0   0.0   0.0   0.0   0.0   0.0
 0.0  0.0  0.0  1.0  0.0  0.0  0.0      0.0   0.0   0.0   0.0   0.0   0.0
 0.0  0.0  0.0  0.0  1.0  0.0  0.0      0.0   0.0   0.0   0.0   0.0   0.0
 0.0  0.0  0.0  0.0  0.0  1.0  0.0  …   0.0   0.0   0.0   0.0   0.0   0.0
 0.0  0.0  0.0  0.0  0.0  0.0  1.0      0.0   0.0   0.0   0.0   0.0   0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0      0.0   0.0   0.0   0.0   0.0   0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0      0.0   0.0   0.0   0.0   0.0   0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0      0.0   0.0   0.0   0.0   0.0   0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  …   0.0   0.0   0.0   0.0   0.0   0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0      0.0   0.0   0.0   0.0   0.0   0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0      0.0   0.0   0.0   0.0   0.0   0.0
 ⋮          

In [10]:
N = 10

y = 2*ones(2*N*(N-1))
y[50] = 0.5
#y[51] = 0.5
y[52] = 0.5
y[53] = 0.5
y[54] = 0.5
y[55] = 0.5
y[56] = 0.5
y[57] = 0.5
y[58] = 0.5
y[59] = 0.1

D1 = speye(N-1,N) - spdiagm(ones(N-1),1,N-1,N)
D = [ kron(D1, speye(N)); kron(speye(N), D1) ]
i, j = N*1 + 2, N*7+7
b = zeros(N^2); b[i], b[j] = 1, -1
v = (D' * spdiagm(y) * D) \ b
v[i] - v[j]


0.9328416941307824

In [7]:
vs = hcat(v[1:10],v[11:20],v[21:30],v[31:40],v[41:50],v[51:60],v[61:70],v[71:80],v[81:90],v[91:100])

10×10 Array{Float64,2}:
 4.1476   4.14601  4.05914  3.96948  …  3.72718  3.67688  3.64739  3.63353
 4.1492   4.23128  4.06193  3.96021     3.69097  3.65608  3.63175  3.61968
 4.06872  4.06798  3.99709  3.92533     3.65619  3.62472  3.60384  3.59375
 3.98897  3.97481  3.93314  3.88171     3.6144   3.58277  3.56514  3.55774
 3.92339  3.90917  3.87893  3.8386      3.56243  3.52684  3.51621  3.51434
 3.87203  3.85954  3.83483  3.80034  …  3.5      3.44595  3.45851  3.46906
 3.83315  3.82213  3.80051  3.76934     3.43883  3.29844  3.40282  3.43433
 3.80529  3.79533  3.77572  3.74696     3.45754  3.40615  3.42002  3.4311 
 3.78738  3.77819  3.7601   3.73349     3.47636  3.44859  3.44002  3.43895
 3.77866  3.76995  3.75299  3.72892     3.51433  3.47181  3.45253  3.44574

In [8]:
heatmap(vs)

<?xml version="1.0" encoding="utf-8"?>
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 2 
 
 
 4 
 
 
 6 
 
 
 8 
 
 
 10 
 
 
 2 
 
 
 4 
 
 
 6 
 
 
 8 
 
 
 10 
 
 
<image width="491" height="364" xlink:href="data:;base64,
iVBORw0KGgoAAAANSUhEUgAAAesAAAFsCAYAAADsRpHBAAAIKElEQVR4nO3XO44sSQGG0cqq7Nel
mSsxQiCNwMFCrAAkFoEB22BbWLOGwcfCBeHggBiYMRr6dnc9cLBxoqX4snTOCv5QZtZXsXz1i19d
dlfgdN7PnjDs5Xgze8Kw/7xt/wxPV3CGP377OHvCsL88nWdPGPb18dPsCcOedy+zJww77k6zJwzb
fuEA4MqJNQDEiTUAxIk1AMSJNQDEiTUAxIk1AMSJNQDEiTUAxIk1AMSJNQDEiTUAxIk1AMSJNQDE
iTUAxIk1AMSJNQDEiTUAxIk1AMSJNQDEiTUAxIk1AMSJNQDEiTUAxIk1AMSJNQDEiTUAxIk1AMSJ
NQDEiTUAxIk1AMSJNQDEiTUAxIk1AMSJNQDEiTUAxK3r/jx7A/9zuIJnsV8usycMu+yW2ROG/fD+
OHvCsD98+zZ7wrB/755nTxj2tmz/XboGbtYAECfWABAn1gAQJ9YAECfWABAn1gAQJ9YAECfWABAn
1gAQJ9YAECfWABAn1gAQJ9YAECfWABAn1gAQJ9YAECfWABAn1gAQJ9YAECfWABAn1gAQJ9YAECfW
ABAn1gAQJ9YAECfWABAn1gAQJ9YAECfWABAn1gAQJ9YAECfWABAn1gAQJ9YAECfWABC33t28zt7w
Lg6nw+wJwy6XZfaEYa+H7T+HdX+ePWHY7WH7Z3jevc2eMOzr/d9mTxh2u3uYPWHYzeVu9oRhbtYA
ECfWABAn1gAQJ9YAECfWABAn1gAQJ9YAECfWABAn1gAQJ9YAECfWABAn1gAQJ9YAECfWABAn1gAQ
J9YAECfWABAn1gAQJ9YAECfWABAn1gAQJ9YAECfWABAn1gAQJ9YAECfWABAn1gAQJ9YAECfWABAn
1gAQJ9YAECfWABAn1gAQJ9YAECfWABAn1gAQtz7cv8ze8C5Ox8PsCcP2+8vsCcPOl2X2hGEvx3X2
hGH3h+2f4Xl5nj1h2F+ffj97wrAvHn85e8Kwu9397AnD3KwBIE6sASBOrAEgTqwBIE6sASBOrAEg
TqwBIE6sASBOrAEgTqwBIE6sASBOrAEgTqwBIE6sASBOrAEgTqwBIE6sASBOrAEgTqwBIE6sASBO
rAEgTqwBIE6sASBOrAEgTqwBIE6sASBOrAEgTqwBIE6sASBOrAEgTqwBIE6sASBOrAEgTqwBIE6s
ASBufXx8mr3hXRyP6+wJw9ZPx9kT2O12b6fD7AnDPp22/z38aPl89oRhhw+/mT1h2O3pdvaEYbfL
9r9pN2sAiBNrAIgTawCIE2sAiBNrAIgTawCIE2sAiBNrAIgTawCIE2sAiBNrAIgTawCIE2sAiBNr
AIgTawCIE2sAiBNrAIgTawCIE2sAiBNrAIgTawCIE2sAiBNrAIgTawCIE2sAiBNrAIgTawCIE2sA
iBNrAIgTawCIE2sAiBNrAIgTawCIE2sAiBNrAIhbP/v+v2ZveBfH15vZE4Z9evowe8KwZbnMnjDs
dN7+f9i382H2hGFfPHx39oRhj6+fz54w7O2y/W/6Gmz/VwkArpxYA0CcWANAnFgDQJxYA0CcWANA
nFgDQJxYA0CcWANAnFgDQJxYA0CcWANAnFgDQJxYA0CcWANAnFgDQJxYA0CcWANAnFgDQJxYA0Cc
WANAnFgDQJxYA0CcWANAnFgDQJxYA0CcWANAnFgDQJxYA0CcWANAnFgDQJxYA0CcWANAnFgDQJxY
A0CcWANA3Prhx3+fveFdXF7X2ROG3f7z4+wJw5blMnvCsNP5MHvCsONp+2f4wf3236WHwzJ7wrBP
p+2f4bT9V8nNGgDqxBoA4sQaAOLEGgDixBoA4sQaAOLEGgDixBoA4sQaAOLEGgDixBoA4sQaAOLE
GgDixBoA4sQaAOLEGgDixBoA4sQaAOLEGgDixBoA4sQaAOLEGgDixBoA4sQaAOLEGgDixBoA4sQa
AOLEGgDixBoA4sQaAOLEGgDixBoA4sQaAOLEGgDixBoA4tb1pw+zN7yTy+wBw/Z/+sfsCcPOx8Ps
CcNeX+5mTxj2+noze8Kw790dZ08Ytu63/z08H5fZE4YdL9s/g5s1AMSJNQDEiTUAxIk1AMSJNQDE
iTUAxIk1AMSJNQDEiTUAxIk1AMSJNQDEiTUAxIk1AMSJNQDEiTUAxIk1AMSJNQDEiTUAxIk1AMSJ
NQDEiTUAxIk1AMSJNQDEiTUAxIk1AMSJNQDEiTUAxIk1AMSJNQDEiTUAxIk1AMSJNQDEiTUAxIk1
AMSJNQDEiTUAxK0vP/v57A3v4u4nv549Ydjhy9/OnjDs9pun2ROG3X3z2ewJw9b1O7MnDPt48zZ7
Arvd7rBs/073dt7+GbZ/AgC4cmINAHFiDQBxYg0AcWINAHFiDQBxYg0AcWINAHFiDQBxYg0AcWIN
AHFiDQBxYg0AcWINAHFiDQBxYg0AcWINAHFiDQBxYg0AcWINAHFiDQBxYg0AcWINAHFiDQBxYg0A
cWINAHFiDQBxYg0AcWINAHFiDQBxYg0AcWINAHFiDQBxYg0AcWINAHHr7nKeveFdvPz5d7MnDLu7
gmexvznOnjBs2V9mTxh2Oh1mTxj28fZl9oRhr+ft34eO52X2hGHL7gp+W2cPAAD+P7EGgDixBoA4
sQaAOLEGgDixBoA4sQaAOLEGgDixBoA4sQaAOLEGgDixBoA4sQaAOLEGgDixBoA4sQaAOLEGgDix
BoA4sQaAOLEGgDixBoA4sQaAOLEGgDixBoA4sQaAOLEGgDixBoA4sQaAOLEGgDixBoA4sQaAOLEG
gDixBoA4sQaAOLEGgLj/AsB5i8XdPk4qAAAAAElFTkSuQmCC
" transform="translate(29, 12)"/>
 
 
 
 
 
 
 
<image width="18" height="364" xlink:href="data:;base64,
iVBORw0KGgoAAAANSUhEUgAAABIAAAFsCAYAAADBkelSAAACHUlEQVR4nO2c223EMAwEqUD9V5Eu
4yOvBPpjEAwIqoCF9kU5vljnyd8KYP0QIBERN+thgAoC4qhVzqVmcw0Te7BGHLWgkk0BgdQo1yZr
lH8Q0Ca7Wxy1Ux8GKBICOhAQaT+lESQ2aD9Gbe1vgU4mAiSkRgEpk824NjnZRvsh1yj7la6N1Qi0
35ZsnWtC+yORF1pxo3zUMNcYjZTUVqMeCMFBqUFAUGeN1HRA5Ds2CKjyIEBK+xlqt8qnEUSNAiLf
+Y+lFslgTdaImkc3itmUkJpxZm+ym3XLppHwOKI0Eh5HXPt1gw2035Zs0P6x7QeT7aO2rrVAtooY
2++z33aukf8PKSutUKNN9j8C5WrUraXWL18gZ2s09mlk8DzaZPdAQvtDRk1oP/TjupMaZT+Uo8Gl
NdpPAQmpYa7pks2VFhtsOo249iMwS+3NMs5sBEbZ/qXWA/ke2AfPbIya8WEUAtJVZO3vF2g/g6Oc
2XM1AqnZkg0eRxAQtSOlRmt/s4TUVqMXQAyOcmbr5pFu1N6CPqoRJntwaXU5MrZfl+zB1MCfM6Dv
sn3n2s7sF0A6apTYGDWhRkmVVpjswa5R1Ar6etmo0cGo2a4JoXYE2n909nPJttkPltZ2/xGYbOge
LZ/9Oo2WWr/A0kI34GA7Iv/KnksNm0eDNeKo6dq/rvV

In [57]:
# define the Lorenz attractor
mutable struct Lorenz
    dt; σ; ρ; β; x; y; z
end

function step!(l::Lorenz)
    dx = l.σ*(l.y - l.x)       ; l.x += l.dt * dx
    dy = l.x*(l.ρ - l.z) - l.y ; l.y += l.dt * dy
    dz = l.x*l.y - l.β*l.z     ; l.z += l.dt * dz
end

attractor = Lorenz((dt = 0.02, σ = 10., ρ = 28., β = 8//3, x = 1., y = 1., z = 1.)...)


# initialize a 3D plot with 1 empty series
plt = plot3d(1, xlim=(-25,25), ylim=(-25,25), zlim=(0,50),
                title = "Lorenz Attractor", marker = 2)

# build an animated gif by pushing new points to the plot, saving every 10th frame
@gif for i=1:1500
    step!(attractor)
    push!(plt, attractor.x, attractor.y, attractor.z)
end every 10

LoadError: syntax: assignment not allowed inside tuple